sonar.projectKey=rick-morty
sonar.projectName=Rick and Morty App
sonar.projectVersion=1.0

# Directorios fuente
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx

# Encoding
sonar.sourceEncoding=UTF-8